# Generated by Django 4.2.10 on 2026-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('HERO', 'Main Editorial Hero Background Image'), ('STORY', 'Brand Story Section Image'), ('PROMO', 'Promotional Banner Image')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
