services:
  - type: web
    name: the-valory-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: the-valory-db
          property: connectionString

databases:
  - name: the-valory-db
    databaseName: the_valory
    user: valory_admin
    plan: free
