# Generated by Django 4.2.10 on 2026-08-12 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Claim ID')),
                ('damage_description', models.TextField(help_text='Detailed description of product damage.')),
                ('unboxing_video_url', models.URLField(blank=True, help_text='Link to unboxing video (Google Drive, Dropbox, YouTube, etc.)', max_length=500)),
                ('unboxing_video_file', models.FileField(blank=True, null=True, upload_to='refunds/videos/')),
                ('photo_evidence_1', models.ImageField(upload_to='refunds/photos/')),
                ('photo_evidence_2', models.ImageField(blank=True, null=True, upload_to='refunds/photos/')),
                ('status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('CLAIM_SUBMITTED', 'Claim Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUND_PROCESSED', 'Refund Processed')], db_index=True, default='CLAIM_SUBMITTED', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_claims', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_claim', to='orders.order')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
