# Generated by Django 4.2.10 on 2026-08-12 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('SHIPPING', 'Shipping Policy'), ('REFUND', 'Refund Policy'), ('RETURN_EXCHANGE', 'Return & Exchange Policy'), ('ORDER', 'Order Cancellation & Terms'), ('GENERAL', 'General Terms & Conditions'), ('TERMS', 'Terms of Service')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML or Markdown policy text.')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('acceptance_type', models.CharField(choices=[('SIGNUP', 'Account Signup Agreement'), ('CHECKOUT', 'Checkout Terms Agreement'), ('REFUND_CLAIM', 'Refund Claim Agreement')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
